version: '3.7'

services:
  movie_service:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/opt/
    ports:
      - 8000:8000
    environment:
      # settings for db await, instead a hardcoded URI
      - DATABASE=postgres
      - SQL_HOST=movie_db
      - SQL_PORT=5432
      # todo: URI transformer
      - DATABASE_URI=postgresql://hello_world:hello_world@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - movie_db

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_world
      - POSTGRES_PASSWORD=hello_world
      - POSTGRES_DB=movie_db_dev
    ports:
      - 5432:5432

volumes:
  postgres_data_movie:
  postgres_data_cast:
